# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Frontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Frontend
    pod 'Alamofire'
    pod 'GoogleSignIn'
    pod 'Kingfisher'
    pod 'ImagePicker'
    pod 'lottie-ios'
    pod 'SnapKit'
    pod 'Tactile'

end
